### ISSUE TITLE
Add robot-side Bling subsystem

### ISSUE THREAD

**Issue by kevlam2706** [FRC2706/2017-2706-Robot-Code#16]
Add a Subsystem class to support the Bling. It will need to maintain a link to the Arduino via RS232 to tell it what to signal.

There is existing code that we wrote from 2994 that we can port over into the command-based robot code.

https://github.com/FRC2994/FRC-2015/blob/master/src/ca/team2994/frc/robot/Bling.java

**Comment by kevlam2706** [comment]
Here's the link to wpilib's tutorial on command-based programming:

https://wpilib.screenstepslive.com/s/4485/m/13809/l/599732-what-is-command-based-programming

We want to build a Subsystem that can later be controlled by Commands.

**Comment by kevlam2706** [comment]
We will need to get a serial cable to connect the RoboRio to one of the Arduino boards (to be later replaced by a Roboduino). Hopefully @LlamaBot9000 (miniKev) can help us with this.

**Comment by kajames** [comment]
Kevin:

Found some bling interface code from 2994 -
https://github.com/FRC2994/FRC-2015/blob/927aa2e77c47a2a32f1878d380ce181c6c7583dd/src/ca/team2994/frc/robot/Bling.java

Ken.

**Comment by KyleRAnderson** [comment]
@greyingjay in the example code you give me, they are referring to a boolean variable called "blingport". What are we going to use for this? I think that this variable refers to the port between the arduino and the roborio, so are we also going to have something similar? `Subsystem.blingPort.writeString("X");`, `if (Subsystem.blingPort != null)`

**Comment by Ketchperiment** [comment]
Is it just a USB B cable that we need or is there something special to interface with the roborio (that goes in the same port as the navx)

**Comment by Ketchperiment** [comment]
@eAUE try this link, it is a tutorial for the I2C connection code

**Comment by KyleRAnderson** [comment]
This is well under way. Should be committing a good version soon.

**Comment by KyleRAnderson** [comment]
Completed in #32
