### ISSUE TITLE
Add Climber subsystem

### ISSUE THREAD

**Issue by kevlam2706** [FRC2706/2017-2706-Robot-Code#17]
Add a new "Subsystem" class to represent the climber mechanism.

For information on how command-based programming works, and what a Subsystem is, here's a good tutorial:

https://wpilib.screenstepslive.com/s/4485/m/13809/l/599732-what-is-command-based-programming

**Comment by greyingjay** [comment]
Trying to assign to Lara, Ellena, and Dana. I'm not sure I know all of your github usernames!

**Comment by wakandacat** [comment]
We need to do:
- [x] motor up or stop
- [ ] current sensor
- [x] control continuous or on demand

**Comment by kevlam2706** [comment]
The climber works! Just a few tweaks left to do including figuring out the Climb Automatically algorithm (getting the right current sensor values, etc)

**Comment by kevlam2706** [comment]
Closing this issue, I'm creating new ones with updated to-do lists.
