### ISSUE TITLE
Update Camera code to talk to 2017 Trackerbox

### ISSUE THREAD

**Issue by kevlam2706** [FRC2706/2017-2706-Robot-Code#18]
Update the Camera subsystem class to talk to the Trackerbox using the 2017 protocol.

**Comment by greyingjay** [comment]
Should we move the Camera from being a single class to being its own Subsystem?

**Comment by cnnradams** [comment]
It was already a subsystem, by the way I deleted a ton of useless code from
camera like the servo stuff but I don't know if you want me to merge it

**Comment by ounsworth** [comment]
In an email @greyingjay asked:

> Should we move the Camera from being a single class to being its own Subsystem?

As open source software, I would rather that the Java, C++, (and python if I ever write one) client code in [TrackerBox2](https://github.com/FRC2706/TrackerBox2/) repo remain standalone and not depend on WPILib or wtv. If nothing else, it allows us to do debugging like Morgan did where a laptop acts as the client. It also allows us to add other devices to the network that act as clients to the trackerbox.

I was imagining that you'd copy [TrackerBox2.java](https://github.com/FRC2706/TrackerBox2/tree/master/JavaWrapper) into the robot code and write a subsystem that has a

```java
public static TrackerBox2 trackerbox;
```

**Comment by kevlam2706** [comment]
Sounds good. The Camera Subsystem code itself should just include the trackerbox java file and use it like a black box to communicate with the other side.

Connor, I realized after I wrote the other comment that it was already a Subsystem. Yes please merge your changes.

**Comment by ounsworth** [comment]
Yeah, please treat the trackerbox java file as a black box. That allows us to change the network protocol or wtv and just say "robot people, here's a new trackerbox java file. Drop it in and you're good to go."

**Comment by kevlam2706** [comment]
I think this is done! Thanks to @MatEdwards and @BookSmart123 for all your work on this.
