### ISSUE TITLE
Battery Status Level Indicator at Startup

### ISSUE THREAD

**Issue by KyleRAnderson** [FRC2706/2017-2706-Robot-Code#22]
It would be great if the level of the robot's battery was indicated by the bling lights when the robot is first turned on. This indicator would last around 10 seconds (up for debate) after which the bling would enter its usual behaviour.

**Comment by kevlam2706** [comment]
I like it. I think the best way to do this would be to implement a generic graph function in the Bling subsystem that you could use to graph a value as a percentage. 0% would display no LEDs, 100% would light up the whole strip.

Bling.showBarGraph(0.5); // show 50%

You could even get fancy by changing the color depending on the percentage. Say, show it in red if it's less than 50%. Show it in green if it's more than 50%.

Then we could have a Command elsewhere that reads the battery voltage, determines the percentage, and calls the Bling subsystem to display it.

**Comment by KyleRAnderson** [comment]
Yeah, I was thinking of something like that.

**Comment by KyleRAnderson** [comment]
There is now a battery indication command, it is now about integration with the sensors.

**Comment by KyleRAnderson** [comment]
I have a couple methods of reading [State of Charge](http://batteryuniversity.com/learn/article/how_to_measure_state_of_charge) with several methods.

**Comment by KyleRAnderson** [comment]
This is done and will be merged in #38. Not super accurate but close enough.
