### ISSUE TITLE
Command for easy vibration feedback

### ISSUE THREAD

**Issue by KyleRAnderson** [FRC2706/2017-2706-Robot-Code#24]
The bling subsystem, as it is being used to both communicate things to the driver as well as for its amazing looks, should work with the vibration feedback to communicate things to the drivers.

**Comment by kevlam2706** [comment]
Cool, and this is fine, but let's make sure we stick with the Command based framework when you do the integration.

https://wpilib.screenstepslive.com/s/4485/m/13809/l/599732-what-is-command-based-programming

**Comment by KyleRAnderson** [comment]
@greyingjay  I was thinking of making nice commands for the rumble like `setRumble(double timeOn, double timeOff, int repeatCount)` which would allow us to set rumble patterns easily from anywhere. I'm debating where I should put this command. I could just put it as part of the bling subsystem, but I feel like it would belong more somewhere else.

**Comment by kevlam2706** [comment]
Yes, that doesn't sound like it belongs in Bling. That sounds like part of the operator interface.

**Comment by KyleRAnderson** [comment]
Alright. Thanks.

**Comment by kevlam2706** [comment]
Keep up the good work! You are asking great questions.

**Comment by KyleRAnderson** [comment]
Renamed this to "Command for easy vibration feedback" to better represent what it will do.

**Comment by KyleRAnderson** [comment]
This was completed and will be merged with #38
