### ISSUE TITLE
Bling Subsystem will show when it is time to climb

### ISSUE THREAD

**Issue by KyleRAnderson** [FRC2706/2017-2706-Robot-Code#34]
After we have determined a time frame in which our robot will make the climb, it would be nice for the bling subsystem to give indications as to when we should:
- Head over to make the climb (as time passes, colour would shift from green to red to show how much time is left to complete this).
- Start the climb (again, colour shifting)

**Comment by kevlam2706** [comment]
Interesting idea! But you may want to check with the drive team (Gabby is the coach) to see if they would like this. If it's useful, let's do it, but if they would prefer something else, we don't want to risk putting too much signalling into the robot that could confuse the drive team.

**Comment by KyleRAnderson** [comment]
@greyingjay agreed. Just an idea so that I don't forget the ideas I have. 

@GabbyGenereux take a look and tell me what you think.

**Comment by GabbyGenereux** [comment]
Awesome idea Kyle! I think the best way that something like this could be done is (if possible), have the bling light up a certain color (like green) when the climbing mechanism has attached to the rope and is ready for climbing. There are a fair number of timers around the field, so I don't think a countdown with the bling is necessary, but it would be nice to have a confirmation that the system is ready for us to start climbing. Given circumstances there may (although unlikely) be matches where we won't climb, and focus on doing something else instead.

**Comment by KyleRAnderson** [comment]
This will be part of #43.
