### ISSUE TITLE
Curve Drive to a location

### ISSUE THREAD

**Issue by cnnradams** [FRC2706/2017-2706-Robot-Code#35]
I did some math and came up with this

y(x) = ax^3 + bx^2 + cx + d

two points: (0,0) and (4,4)

therefore 0a + 0b + 0c + d = 0
d = 0

therefore 64a + 16b + 4c + d = 4

slope of two tangents:

first is x = 0, but thats undefined so lets do y = 100x therefore m = 100
y\`(0) = 100
second is lets say 60 degrees right, so slope is 1.73205 (tan 60)
y\`(4) = 1.73205

y`(x) = 3ax^2 + 2bx + c

3a(0)^2 + 2b(0) + c = 100
therefore c = 100

3a(4)^2 + 2b(4) + c = 1.73205

48a + 8b + c = 1.73205

so now we line up the equations

d = 0
64a + 16b + 4c + d = 4
c = 100
48a + 8b + c = 1.73205

64a + 16b + 400 = 4
48a + 8b + 100 = 1.73205

64a + 16b + 400 = 4
96a + 16b + 200 = 3.4641

-32a + 0 + 200 = 0.5359

-32a = -199.4641

a = 6.233253125

64(6.233253125) + 16b + 400 = 4

398.9282 + 16b + 400 = 4

16b = -794.9282

b = -49.6830125

therefore y = 6.233253125x^3 - 49.6830125x^2 + 100x

I mean... the graph checks out its just not quite what we want... Any ideas?

**Comment by cnnradams** [comment]
If I change the math to have the starting slope as two it makes a more likeable curve but then you have to turn at the start :(
y(x) = ax^3 + bx^2 + cx + d

two points: (0,0) and (4,4)

therefore 0a + 0b + 0c + d = 0
d = 0

therefore 64a + 16b + 4c + d = 4

slope of two tangents:

first is x = 0, but thats undefined so lets do y = 2x therefore m = 2
y\`(0) = 2
second is lets say 60 degrees right, so slope is 1.73205 (tan 60)
y\`(4) = 1.73205

y`(x) = 3ax^2 + 2bx + c

3a(0)^2 + 2b(0) + c = 2
therefore c = 2

3a(4)^2 + 2b(4) + c = 1.73205

48a + 8b + c = 1.73205

so now we line up the equations

d = 0
64a + 16b + 4c + d = 4
c = 100
48a + 8b + c = 1.73205

64a + 16b + 8 = 4
48a + 8b + 2 = 1.73205

64a + 16b + 8 = 4
96a + 16b + 4 = 3.4641

-32a + 0 + 4 = 0.5359

-32a = -3.4641

a = 0.108253125

64(0.108253125) + 16b + 8 = 4

6.9282 + 16b + 8 = 4

16b = -10.9282

b = -0.6830125

therefore y = 0.108253125x^3 - 0.6830125x^2 + 2x

**Comment by cnnradams** [comment]
![image](https://cloud.githubusercontent.com/assets/10487992/22914702/01d6c614-f240-11e6-9906-f4f4902f69c0.png)

**Comment by ounsworth** [comment]
I did some math too and came up with general formulas. Looking at the graphs, I don't think they are 100% right (I probably made some algebra copy mistakes)
![img_20170213_235118](https://cloud.githubusercontent.com/assets/5394395/22915859/52b41476-f248-11e6-955d-4a90446c9faf.jpg)

![img_20170213_235135](https://cloud.githubusercontent.com/assets/5394395/22915884/8668a39a-f248-11e6-9fef-d0441cba69fc.jpg)


![img_20170213_235235](https://cloud.githubusercontent.com/assets/5394395/22915830/1b2324a2-f248-11e6-8d0c-83f9d1a70fa7.jpg)

So while this will work, the weird S-curve thing really isn't ideal. Maybe it's time to look into other families of curves on Chief.

Either way, playing with equations of slope is calculus. I'm super impressed that you're dabbling in calculus!

**Comment by cnnradams** [comment]
So you had your slope at 0, which is actually a robot start of 90 degrees, do you suggest just rotating the graph 90 degrees left or what?

**Comment by kevlam2706** [comment]
I wonder if it would make it easier just to do that, and use a slope
of 0, rather than have a near-infinite slope.

**Comment by ounsworth** [comment]
Yeah, I "rotated my graph paper" so that the robot starts off pointing down
the X-axis for two reasons:

1) Vertical lines are problematic (try putting tan(90) into your
calculator...). They have infinite slope and the math blows up, Java throws
exceptions, etc.

2) By setting the slope at (0,0) to 0, the equation "y = ax^3 + bx^2 + cx +
d" collapses to  "y = ax^3 + bx^2", which makes the rest of the algebra
much less messy!
