### ISSUE TITLE
Bling Displays multiple things during teleop automatically

### ISSUE THREAD

**Issue by KyleRAnderson** [FRC2706/2017-2706-Robot-Code#43]
I think it would be helpful for the bling subsystem to automatically display certain patterns during teleop. This would include 
- [x] Whenever we are _X_ metres away from the gear drop off, show the distance to the gear peg.
- [x] When we are ready to receive a gear, show this.
- [x] At the end of teleop period, display when the robot is ready to climb.

This would integrate with the  GearHandler and Climb subsystems, and would continually run a command during teleop that gets all of the parameters listed above. The subsystems mentioned should have a command like `GearHandler.getStatus()` to make it easy for the bling subsystem to get the parameter.

I was thinking that the `GearHandler.getStatus()` method would return a string depending on the state of the subsystem like "loaded" if the robot has a gear, "ready" if it is ready to get a gear or "not ready" if it isn't ready to get a gear.

**Comment by wakandacat** [comment]
@eAUE we did what you asked for the gear handler. See #48

**Comment by KyleRAnderson** [comment]
@wakandacat thanks. Great job too by the way!
