### ISSUE TITLE
Fix backing up from the loading station

### ISSUE THREAD

**Issue by KyleRAnderson** [FRC2706/2017-2706-Robot-Code#72]
Whenever the robot backs up from receiving a gear at the loading station, because it is in close proximity to an object it begins to display peg line-up patterns. This can be confusing as they will display red blinking lights whereas it should start displaying the rainbow "I have a gear" pattern.

**Comment by ounsworth** [comment]
Out of curiosity, what did you need to fix to get overall bling working?

**Comment by KyleRAnderson** [comment]
I think Ken did something and I fixed how my side of the code worked a little bit.
